#---
#- name: Assign IP Addresses to interfaces
#  netbox.netbox.netbox_ip_address:
#    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
#    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"
#    data: "{{ ip }}"
#    state: present
#  loop: "{{ ip_addresses }}"
#  loop_control:
#    loop_var: ip
#    label: "{{ ip['assigned_object']}}"

---
- name: Create IP address and assign a nat_inside IP
  netbox.netbox.netbox_ip_address:
        netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"
        data:
          address: "{{ item.prefix }}"
          assigned_object:
            name: "{{ item.assigned_object.name }}"
            device: "{{item.assigned_object.device}}"
  loop: "{{ ip_addresses}}"  # 使用loop读取接口配置
  loop_control:
    loop_var: item
    label: "{{ item['assigned_object']}}"