#- hosts: NX9300  # 针对NX9300设备的操作
#  gather_facts: false  # 不收集主机的事实信息，加快执行速度
#  connection: network_cli  # 使用网络设备的CLI方式进行连接
#  vars_files:
#    - vlan_to_device_interface_data.yaml # 导入包含配置数据的YAML文件
#
#  tasks:
#    # 为设备接口分配 VLAN
#    - name: "Assign VLAN to interface"
#      netbox.netbox.netbox_device_interface:  # 更新为新的模块名称
#        netbox_url: "http://192.168.219.42:8000"
#        netbox_token: "0123456789abcdef0123456789abcdef01234567"
#        data:
#          name: "{{ item.interface_name }}"  # 接口名称
#          device: "{{ inventory_hostname }}"  # 使用inventory中的设备名称
#          mode: "access"                     # 接口模式 (access 或 trunk)
#          untagged_vlan:
#            name: "{{ item.vlan_name }}"      # 分配的VLAN名称
#            vid: "{{ item.vlan_vid }}"        # VLAN ID
#        state: present
#      loop: "{{ NX9300[inventory_hostname].interfaces }}"




- hosts: NX9300  # 针对NX9300设备的操作
  gather_facts: false  # 不收集主机的事实信息，加快执行速度
  connection: network_cli  # 使用网络设备的CLI方式进行连接
  vars_files:
    - vlan_to_device_interface_data.yaml # 导入包含配置数据的YAML文件

  tasks:
    # 为设备接口分配 VLAN
    - name: "Assign VLAN to interface"
      netbox.netbox.netbox_device_interface:  # 更新为新的模块名称
        netbox_url: "http://192.168.219.42:8000"
        netbox_token: "0123456789abcdef0123456789abcdef01234567"
        data:
          name: "{{ interface.interface_name }}"  # 接口名称
          device: "{{ inventory_hostname }}"  # 使用inventory中的设备名称
          mode: "access"                     # 接口模式 (access 或 trunk)
          untagged_vlan:
            name: "{{ interface.vlan_name }}"      # 分配的VLAN名称
            vid: "{{ interface.vlan_vid }}"        # VLAN ID
        state: present
      loop: "{{ NX9300[inventory_hostname].interfaces }}"
      loop_control:
        loop_var: interface
        label: "{{ interface['vlan_vid']}}"